// <auto-generated />
using System;
using App.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.DAL.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Osavõtja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eesnimi")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EraisikuLisainfo")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("EttevõtteJuriidilineNimi")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EttevõtteRegistrikood")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("EttevõttestTulevateOsavõtjateArv")
                        .HasColumnType("int");

                    b.Property<string>("Isikukood")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("OsavotumaksuMaksmiseViisId")
                        .HasColumnType("int");

                    b.Property<int>("OsavõtjaTüüp")
                        .HasColumnType("int");

                    b.Property<string>("Perekonnanimi")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ÜritusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OsavotumaksuMaksmiseViisId");

                    b.HasIndex("ÜritusId");

                    b.ToTable("Osavõtjad");
                });

            modelBuilder.Entity("App.Domain.OsavõtumaksuMaksmiseViis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OsavõtumaksuMaksmiseViisiNimetus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("OsavõtumaksuMaksmiseViisid");
                });

            modelBuilder.Entity("App.Domain.Üritus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Koht")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OsavõtjateArv")
                        .HasColumnType("int");

                    b.Property<DateTime>("Toimumisaeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("ÜrituseNimi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Üritused");
                });

            modelBuilder.Entity("App.Domain.Osavõtja", b =>
                {
                    b.HasOne("App.Domain.OsavõtumaksuMaksmiseViis", "OsavotumaksuMaksmiseViis")
                        .WithMany()
                        .HasForeignKey("OsavotumaksuMaksmiseViisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Üritus", null)
                        .WithMany("Osavõtjad")
                        .HasForeignKey("ÜritusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OsavotumaksuMaksmiseViis");
                });

            modelBuilder.Entity("App.Domain.Üritus", b =>
                {
                    b.Navigation("Osavõtjad");
                });
#pragma warning restore 612, 618
        }
    }
}
